openapi: 3.1.0
info:
  title: Reminders
  description: Needs a description.
paths:
  /reminders.add:
    post:
      tags:
        - reminders
      description: Creates a reminder.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/reminders.add
      operationId: reminders_add
      parameters:
        - name: token
          in: header
          description: 'Authentication token. Requires scope: `reminders:write`'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - text
                - time
              type: object
              properties:
                text:
                  type: string
                  description: The content of the reminder
                time:
                  type: string
                  description: >-
                    When this reminder should happen: the Unix timestamp (up to
                    five years from now), the number of seconds until the
                    reminder (if within 24 hours), or a natural language
                    description (Ex. "in 15 minutes," or "every Thursday")
                user:
                  type: string
                  description: >-
                    The user who will receive the reminder. If no user is
                    specified, the reminder will go to user who created it.
          application/json:
            schema:
              required:
                - text
                - time
              type: object
              properties:
                text:
                  type: string
                  description: The content of the reminder
                time:
                  type: string
                  description: >-
                    When this reminder should happen: the Unix timestamp (up to
                    five years from now), the number of seconds until the
                    reminder (if within 24 hours), or a natural language
                    description (Ex. "in 15 minutes," or "every Thursday")
                user:
                  type: string
                  description: >-
                    The user who will receive the reminder. If no user is
                    specified, the reminder will go to user who created it.
        required: true
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: reminders.add schema
                required:
                  - ok
                  - reminder
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                  reminder:
                    $ref: '#/components/schemas/objs_reminder'
                additionalProperties: false
                description: Schema for successful response from reminders.add method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: reminders.add error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - cannot_parse
                      - user_not_found
                      - cannot_add_bot
                      - cannot_add_slackbot
                      - cannot_add_others
                      - cannot_add_others_recurring
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from reminders.add method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - reminders:write
  /reminders.complete:
    post:
      tags:
        - reminders
      description: Marks a reminder as complete.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/reminders.complete
      operationId: reminders_complete
      parameters:
        - name: token
          in: header
          description: 'Authentication token. Requires scope: `reminders:write`'
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reminder:
                  type: string
                  description: The ID of the reminder to be marked as complete
          application/json:
            schema:
              type: object
              properties:
                reminder:
                  type: string
                  description: The ID of the reminder to be marked as complete
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: reminders.complete schema
                required:
                  - ok
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                additionalProperties: false
                description: Schema for successful response from reminders.complete method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: reminders.complete error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - not_found
                      - cannot_complete_recurring
                      - cannot_complete_others
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from reminders.complete method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - reminders:write
  /reminders.delete:
    post:
      tags:
        - reminders
      description: Deletes a reminder.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/reminders.delete
      operationId: reminders_delete
      parameters:
        - name: token
          in: header
          description: 'Authentication token. Requires scope: `reminders:write`'
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reminder:
                  type: string
                  description: The ID of the reminder
          application/json:
            schema:
              type: object
              properties:
                reminder:
                  type: string
                  description: The ID of the reminder
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: reminders.delete schema
                required:
                  - ok
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                additionalProperties: false
                description: Schema for successful response from reminders.delete method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: reminders.delete error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - not_found
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from reminders.delete method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - reminders:write
  /reminders.info:
    get:
      tags:
        - reminders
      description: Gets information about a reminder.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/reminders.info
      operationId: reminders_info
      parameters:
        - name: token
          in: query
          description: 'Authentication token. Requires scope: `reminders:read`'
          schema:
            type: string
        - name: reminder
          in: query
          description: The ID of the reminder
          schema:
            type: string
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: reminders.info schema
                required:
                  - ok
                  - reminder
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                  reminder:
                    $ref: '#/components/schemas/objs_reminder'
                additionalProperties: false
                description: Schema for successful response from reminders.info method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: reminders.info error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - not_found
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from reminders.info method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - reminders:read
  /reminders.list:
    get:
      tags:
        - reminders
      description: Lists all reminders created by or for a given user.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/reminders.list
      operationId: reminders_list
      parameters:
        - name: token
          in: query
          description: 'Authentication token. Requires scope: `reminders:read`'
          schema:
            type: string
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: reminders.list schema
                required:
                  - ok
                  - reminders
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                  reminders:
                    type: array
                    items:
                      $ref: '#/components/schemas/objs_reminder'
                additionalProperties: false
                description: Schema for successful response from reminders.list method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: reminders.list error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from reminders.list method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - reminders:read
components:
  schemas: {}
