openapi: 3.1.0
info:
  title: Dnd
  description: Needs a description.
paths:
  /dnd.endDnd:
    post:
      tags:
        - dnd
      description: Ends the current user's Do Not Disturb session immediately.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/dnd.endDnd
      operationId: dnd_endDnd
      parameters:
        - name: token
          in: header
          description: 'Authentication token. Requires scope: `dnd:write`'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: dnd.endDnd schema
                required:
                  - ok
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                additionalProperties: false
                description: Schema for successful response from dnd.endDnd method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: dnd.endDnd error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - unknown_error
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from dnd.endDnd method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - dnd:write
  /dnd.endSnooze:
    post:
      tags:
        - dnd
      description: Ends the current user's snooze mode immediately.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/dnd.endSnooze
      operationId: dnd_endSnooze
      parameters:
        - name: token
          in: header
          description: 'Authentication token. Requires scope: `dnd:write`'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: dnd.endSnooze schema
                required:
                  - dnd_enabled
                  - next_dnd_end_ts
                  - next_dnd_start_ts
                  - ok
                  - snooze_enabled
                type: object
                properties:
                  dnd_enabled:
                    type: boolean
                  next_dnd_end_ts:
                    type: integer
                  next_dnd_start_ts:
                    type: integer
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                  snooze_enabled:
                    type: boolean
                additionalProperties: false
                description: Schema for successful response from dnd.endSnooze method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: dnd.endSnooze error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - snooze_not_active
                      - snooze_end_failed
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from dnd.endSnooze method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - dnd:write
  /dnd.info:
    get:
      tags:
        - dnd
      description: Retrieves a user's current Do Not Disturb status.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/dnd.info
      operationId: dnd_info
      parameters:
        - name: token
          in: query
          description: 'Authentication token. Requires scope: `dnd:read`'
          schema:
            type: string
        - name: user
          in: query
          description: User to fetch status for (defaults to current user)
          schema:
            type: string
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: dnd.info schema
                required:
                  - dnd_enabled
                  - next_dnd_end_ts
                  - next_dnd_start_ts
                  - ok
                type: object
                properties:
                  dnd_enabled:
                    type: boolean
                  next_dnd_end_ts:
                    type: integer
                  next_dnd_start_ts:
                    type: integer
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                  snooze_enabled:
                    type: boolean
                  snooze_endtime:
                    type: integer
                  snooze_remaining:
                    type: integer
                additionalProperties: false
                description: Schema for successful response from dnd.info method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: dnd.info error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - user_not_found
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from dnd.info method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - dnd:read
  /dnd.setSnooze:
    post:
      tags:
        - dnd
      description: >-
        Turns on Do Not Disturb mode for the current user, or changes its
        duration.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/dnd.setSnooze
      operationId: dnd_setSnooze
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - num_minutes
                - token
              type: object
              properties:
                token:
                  type: string
                  description: 'Authentication token. Requires scope: `dnd:write`'
                num_minutes:
                  type: string
                  description: Number of minutes, from now, to snooze until.
        required: true
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: dnd.setSnooze schema
                required:
                  - ok
                  - snooze_enabled
                  - snooze_endtime
                  - snooze_remaining
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                  snooze_enabled:
                    type: boolean
                  snooze_endtime:
                    type: integer
                  snooze_remaining:
                    type: integer
                additionalProperties: false
                description: Schema for successful response from dnd.setSnooze method
              example:
                ok: true
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: dnd.setSnooze error schema
                required:
                  - error
                  - ok
                type: object
                properties:
                  callstack:
                    type: string
                    description: 'Note: PHP callstack is only visible in dev/qa'
                  error:
                    type: string
                    enum:
                      - missing_duration
                      - snooze_failed
                      - not_authed
                      - invalid_auth
                      - account_inactive
                      - token_revoked
                      - no_permission
                      - org_login_required
                      - user_is_bot
                      - invalid_arg_name
                      - invalid_array_arg
                      - invalid_charset
                      - invalid_form_data
                      - invalid_post_type
                      - missing_post_type
                      - team_added_to_org
                      - invalid_json
                      - json_not_object
                      - request_timeout
                      - upgrade_required
                      - too_long
                      - fatal_error
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: false
                description: Schema for error response from dnd.setSnooze method
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - dnd:write
  /dnd.teamInfo:
    get:
      tags:
        - dnd
      description: Retrieves the Do Not Disturb status for up to 50 users on a team.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/dnd.teamInfo
      operationId: dnd_teamInfo
      parameters:
        - name: token
          in: query
          description: 'Authentication token. Requires scope: `dnd:read`'
          schema:
            type: string
        - name: users
          in: query
          description: Comma-separated list of users to fetch Do Not Disturb status for
          schema:
            type: string
      responses:
        '200':
          description: Typical success response
          content:
            application/json:
              schema:
                title: Default success template
                required:
                  - ok
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_true'
                additionalProperties: true
                description: >-
                  This method either only returns a brief _OK_ response or a
                  verbose schema is not available for this method.
              example:
                ok: true
                users:
                  U023BECGF:
                    dnd_enabled: true
                    next_dnd_end_ts: 1450423800
                    next_dnd_start_ts: 1450387800
                  W058CJVAA:
                    dnd_enabled: false
                    next_dnd_end_ts: 1
                    next_dnd_start_ts: 1
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: Default error template
                required:
                  - ok
                type: object
                properties:
                  ok:
                    $ref: '#/components/schemas/defs_ok_false'
                additionalProperties: true
                description: >-
                  This method either only returns a brief _not OK_ response or a
                  verbose schema is not available for this method.
              example:
                error: invalid_auth
                ok: false
      security:
        - slackAuth:
            - dnd:read
components:
  schemas: {}
